name: Monolith_Bridge_Test
on:
  repository_dispatch:
    types: [ai_query] # Это кодовое слово

jobs:
  ping_back:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Write Log
        run: |
          echo "Архитектор, Гитхаб на связи! Время: $(date)" > answer.txt
      - name: Push to Repo
        run: |
          git config --global user.email "sputnik@monolith.zero"
          git config --global user.name "Sputnik Agent"
          git add answer.txt
          git commit -m "Signal received"
          git push
